console.log(document.getElementsByTagName('span')[0])
console.dir(document.getElementsByTagName('span')[0])
console.log(document.body.firstChild.nodeName)
console.log(document.body.firstElementChild.nodeName)
let x=console.log(document.getElementsByTagName('span')[0])
console.log(x)
let y=(document.getElementsByTagName('span')[0])
console.dir(y)
console.log(first.innerHTML)
console.log(first.innerHTML = "<i>hey i am italic </i>")
console.log(first.outerHTML)
console.log(first.outerHTML = "<div>hey</div>")
console.log(document.body.firstChild)
console.log(document.body.firstChild.data)
console.log(document.body.firstChild.nodeValue)
console.log(document.body.textContent)
console.log(document.body.firstChild.data)
console.log(first.hidden = false)